steps:
  # Build unified application
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/excel-interview-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/excel-interview-app:latest'
      - 'backend'
    id: 'Build Application'


  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'excel-interview-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/excel-interview-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},GEMINI_API_KEY=${_GEMINI_API_KEY},ENVIRONMENT=production'

# Push images to Google Container Registry
images:
  - "gcr.io/ai-excel-interviewer/excel-interview-app"

# Substitution variables (set in Cloud Build triggers)
substitutions:
  _DATABASE_URL: 'postgresql://user:anirudh@/db?host=/cloudsql/ai-excel-interviewer:us-central1:excel-interview-db'
  _GEMINI_API_KEY: 'AIzaSyAAdSCqdP6ZQfhNaa8iRQBQV-acY-24C9U'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'