version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: excel_interviewer
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod   # store production env here (do not commit)
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_data:/app/static   # persist TTS & reports
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - appnet

  nginx:
    image: nginx:stable
    depends_on:
      - backend
      - frontend
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet

volumes:
  db_data:
  static_data:

networks:
  appnet:
